apiVersion: v1
kind: Pod
metadata:
  name: podjenkins
  labels:
    jenkins: jenkins-pipeline
spec:
  volumes:
  - name: kaniko-secret
    secret:
      secretName: dockercred
      items:
      - key: .dockerconfigjson
        path: config.json
  serviceAccountName: jenkins
  securityContext:
    runAsUser: 0
  containers:
    # - name: jnlp
    #   image: mirantis/jnlp-slave
    #   workingDir: /apps/kubedata/jenkins-agent/
    #   ttyEnabled: true
    #   volumeMounts:
    #     - mountPath: "apps/kubedata/jenkins-agent"
    #       name: sharedvolume
    #   resources:
    #     requests:
    #       memory: "128Mi"
    #       cpu: "500m"
    #     limits:
    #       memory: "1000Mi"
    #       cpu: "500m"
    - name: kaniko
      image: gcr.io/kaniko-project/executor:debug
      imagePullPolicy: Always
      command:
        - sleep
        - "1000"
      tty: true
      volumeMounts:
        - mountPath: /kaniko/.docker 
          name: kaniko-secret
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"
    - name: gradle
      image: gradle
      imagePullPolicy: Always
      ttyEnabled: true
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"  
    - name: helm3
      image: justinrlee/helm3:latest
      imagePullPolicy: Always
      ttyEnabled: true
      command:
        - sleep
      args:
        - 99d
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "1000Mi"
          cpu: "500m"      