apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: priyankapractice
  name: priyankapractice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: priyankapractice
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: priyankapractice
    spec:
      containers:
      - image: "{{ Values.image.repository }}:{{ Values.image.tag }}"
        name: priyankapractice
        resources: {}
status: {}