apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: priyankapractice
  name: priyankasvc
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: priyankapractice
status:
  loadBalancer: {}